# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Trevor Bruner
email: trevorabruner@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site is under construction at the moment and when finished will
  be a portfolio site for Trevor Bruner to showcase his work in
  computer science
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tbruner.github.io/" # the base hostname & protocol for your site
twitter_username: TrevorABruner
github_username:  tbruner

# Build settings
markdown: kramdown

theme: jekyll-theme-slate